### ISSUE TITLE
Missing Output

### ISSUE THREAD

**Issue by stephenway** [imathis/color-hacker#1]
Upgraded Sass and Compass to latest, installed rb-fsevent. 
Added require 'color-hacker' to config.rb
Added @debug(hack-colors(#aaff00 #88cc00 #e8ffbb #669900 #333333 #446600 #88cc00)); to Sass file.
Returned 
file.scss:1 DEBUG: hack-colors(#aaff00 #88cc00 #e8ffbb #669900 #333333 #446600 #88cc00)
I also tried both scale and adjust, with no luck.
Did I miss something?

**Comment by benfrain** [comment]
I'm having the same problem as Stephen - the debug just prints the same values you pass: e.g. DEBUG: hack-colors(#cff09e #a8dba8 #79bd9a #3b8686 #0b486b).

Is this just a syntax problem?
